{
	"schema_version": "1.6.0",
	"id": "BIT-gitlab-2023-6678",
	"modified": "2024-11-05T07:36:31.248Z",
	"published": "2024-04-16T07:22:40.787Z",
	"aliases": [
		"CVE-2023-6678"
	],
	"details": "An issue has been discovered in GitLab EE affecting all versions before 16.8.6, all versions starting from 16.9 before 16.9.4, all versions starting from 16.10 before 16.10.2. It was possible for an attacker to cause a  denial of service using malicious crafted content in a junit test report file.",
	"affected": [
		{
			"package": {
				"ecosystem": "Bitnami",
				"name": "gitlab",
				"purl": "pkg:bitnami/gitlab"
			},
			"severity": [
				{
					"type": "CVSS_V3",
					"score": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:L"
				}
			],
			"ranges": [
				{
					"type": "SEMVER",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "16.8.6"
						},
						{
							"introduced": "16.9.0"
						},
						{
							"fixed": "16.9.4"
						},
						{
							"introduced": "16.10.0"
						},
						{
							"fixed": "16.10.2"
						}
					]
				}
			],
			"database_specific": {
				"source": "https://github.com/bitnami/vulndb/tree/main/data/gitlab/BIT-gitlab-2023-6678.json"
			}
		}
	],
	"references": [
		{
			"type": "WEB",
			"url": "https://gitlab.com/gitlab-org/gitlab/-/issues/434689"
		},
		{
			"type": "WEB",
			"url": "https://hackerone.com/reports/2268037"
		}
	],
	"database_specific": {
		"cpes": [
			"cpe:2.3:a:gitlab:gitlab:*:*:*:*:*:community:*:*",
			"cpe:2.3:a:gitlab:gitlab:*:*:*:*:*:enterprise:*:*",
			"cpe:2.3:a:gitlab:gitlab:*:*:*:*:*:*:*:*",
			"cpe:2.3:a:gitlab:gitlab:*:*:*:*:enterprise:*:*:*"
		],
		"severity": "Medium"
	}
}
