{
	"schema_version": "1.6.0",
	"id": "BIT-gitlab-2020-13310",
	"modified": "2024-11-05T07:36:31.248Z",
	"published": "2024-03-06T11:22:23.680Z",
	"aliases": [
		"CVE-2020-13310"
	],
	"details": "A vulnerability was discovered in GitLab runner versions before 13.1.3, 13.2.3 and 13.3.1. It was possible to make the gitlab-runner process crash by sending malformed queries, resulting in a denial of service.",
	"affected": [
		{
			"package": {
				"ecosystem": "Bitnami",
				"name": "gitlab",
				"purl": "pkg:bitnami/gitlab"
			},
			"severity": [
				{
					"type": "CVSS_V3",
					"score": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H"
				}
			],
			"ranges": [
				{
					"type": "SEMVER",
					"events": [
						{
							"introduced": "1.0.0"
						},
						{
							"fixed": "13.1.3"
						},
						{
							"introduced": "13.2.0"
						},
						{
							"fixed": "13.2.3"
						},
						{
							"introduced": "13.3.0"
						},
						{
							"fixed": "13.3.1"
						}
					]
				}
			],
			"database_specific": {
				"source": "https://github.com/bitnami/vulndb/tree/main/data/gitlab/BIT-gitlab-2020-13310.json"
			}
		}
	],
	"references": [
		{
			"type": "WEB",
			"url": "https://gitlab.com/gitlab-org/cves/-/blob/master/2020/CVE-2020-13310.json"
		},
		{
			"type": "WEB",
			"url": "https://gitlab.com/gitlab-org/gitlab-runner/-/issues/25857"
		},
		{
			"type": "WEB",
			"url": "https://gitlab.com/gitlab-org/gitlab-runner/-/issues/26819"
		}
	],
	"database_specific": {
		"cpes": [
			"cpe:2.3:a:gitlab:gitlab:*:*:*:*:*:*:*:*",
			"cpe:2.3:a:gitlab:gitlab:*:*:*:*:enterprise:*:*:*"
		],
		"severity": "Medium"
	}
}
