{
	"schema_version": "1.6.0",
	"id": "BIT-gitlab-2020-13289",
	"modified": "2024-11-05T07:36:31.248Z",
	"published": "2024-03-06T11:22:48.889Z",
	"aliases": [
		"CVE-2020-13289"
	],
	"details": "A vulnerability was discovered in GitLab versions before 13.1.10, 13.2.8 and 13.3.4. In certain cases an invalid username could be accepted when 2FA is activated.",
	"affected": [
		{
			"package": {
				"ecosystem": "Bitnami",
				"name": "gitlab",
				"purl": "pkg:bitnami/gitlab"
			},
			"severity": [
				{
					"type": "CVSS_V3",
					"score": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:L/I:L/A:N"
				}
			],
			"ranges": [
				{
					"type": "SEMVER",
					"events": [
						{
							"introduced": "8.7.0"
						},
						{
							"fixed": "13.1.10"
						},
						{
							"introduced": "13.2.0"
						},
						{
							"fixed": "13.2.8"
						},
						{
							"introduced": "13.3.0"
						},
						{
							"fixed": "13.3.4"
						}
					]
				}
			],
			"database_specific": {
				"source": "https://github.com/bitnami/vulndb/tree/main/data/gitlab/BIT-gitlab-2020-13289.json"
			}
		}
	],
	"references": [
		{
			"type": "WEB",
			"url": "https://gitlab.com/gitlab-org/cves/-/blob/master/2020/CVE-2020-13289.json"
		},
		{
			"type": "WEB",
			"url": "https://gitlab.com/gitlab-org/gitlab/-/issues/20302"
		}
	],
	"database_specific": {
		"cpes": [
			"cpe:2.3:a:gitlab:gitlab:*:*:*:*:community:*:*:*",
			"cpe:2.3:a:gitlab:gitlab:*:*:*:*:enterprise:*:*:*",
			"cpe:2.3:a:gitlab:gitlab:*:*:*:*:*:*:*:*"
		],
		"severity": "Medium"
	}
}
