{
	"schema_version": "1.6.0",
	"id": "BIT-python-min-2020-15801",
	"modified": "2025-01-16T09:11:50.318088Z",
	"published": "2025-01-16T07:24:07.010Z",
	"aliases": [
		"BIT-python-2020-15801",
		"CVE-2020-15801"
	],
	"details": "In Python 3.8.4, sys.path restrictions specified in a python38._pth file are ignored, allowing code to be loaded from arbitrary locations. The <executable-name>._pth file (e.g., the python._pth file) is not affected.",
	"affected": [
		{
			"package": {
				"ecosystem": "Bitnami",
				"name": "python-min",
				"purl": "pkg:bitnami/python-min"
			},
			"severity": [
				{
					"type": "CVSS_V3",
					"score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H"
				}
			],
			"ranges": [
				{
					"type": "SEMVER",
					"events": [
						{
							"introduced": "3.7.0"
						},
						{
							"fixed": "3.7.9"
						},
						{
							"introduced": "3.8.0"
						},
						{
							"fixed": "3.8.5"
						}
					]
				}
			],
			"database_specific": {
				"source": "https://github.com/bitnami/vulndb/tree/main/data/python-min/BIT-python-min-2020-15801.json"
			}
		}
	],
	"references": [
		{
			"type": "WEB",
			"url": "https://bugs.python.org/issue41304"
		},
		{
			"type": "WEB",
			"url": "https://github.com/python/cpython/pull/21495"
		},
		{
			"type": "WEB",
			"url": "https://security.netapp.com/advisory/ntap-20200731-0003/"
		}
	],
	"database_specific": {
		"cpes": [
			"cpe:2.3:a:python:python:*:*:*:*:*:*:*:*"
		],
		"severity": "Critical"
	}
}
