{
	"schema_version": "1.6.0",
	"id": "BIT-memcached-2020-22570",
	"modified": "2024-11-08T19:58:35.934700Z",
	"published": "2024-11-08T19:14:27.273Z",
	"aliases": [
		"CVE-2020-22570"
	],
	"details": "Memcached 1.6.0 before 1.6.3 allows remote attackers to cause a denial of service (daemon crash) via a crafted meta command.",
	"affected": [
		{
			"package": {
				"ecosystem": "Bitnami",
				"name": "memcached",
				"purl": "pkg:bitnami/memcached"
			},
			"severity": [
				{
					"type": "CVSS_V3",
					"score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H"
				}
			],
			"ranges": [
				{
					"type": "SEMVER",
					"events": [
						{
							"introduced": "1.6.0"
						},
						{
							"fixed": "1.6.3"
						}
					]
				}
			],
			"database_specific": {
				"source": "https://github.com/bitnami/vulndb/tree/main/data/memcached/BIT-memcached-2020-22570.json"
			}
		}
	],
	"references": [
		{
			"type": "WEB",
			"url": "https://github.com/memcached/memcached/issues/636"
		}
	],
	"database_specific": {
		"cpes": [
			"cpe:2.3:a:memcached:memcached:*:*:*:*:*:*:*:*"
		],
		"severity": "High"
	}
}
