{
	"schema_version": "1.6.0",
	"id": "BIT-gitlab-2022-0151",
	"modified": "2024-11-27T19:40:48.342Z",
	"published": "2024-03-06T11:17:03.928Z",
	"aliases": [
		"CVE-2022-0151"
	],
	"details": "An issue has been discovered in GitLab affecting all versions starting from 12.10 before 14.4.5, all versions starting from 14.5.0 before 14.5.3, all versions starting from 14.6.0 before 14.6.2. GitLab was not correctly handling requests to delete existing packages which could result in a Denial of Service under specific conditions.",
	"affected": [
		{
			"package": {
				"ecosystem": "Bitnami",
				"name": "gitlab",
				"purl": "pkg:bitnami/gitlab"
			},
			"severity": [
				{
					"type": "CVSS_V3",
					"score": "CVSS:3.1/AV:N/AC:L/PR:H/UI:N/S:U/C:N/I:H/A:H"
				}
			],
			"ranges": [
				{
					"type": "SEMVER",
					"events": [
						{
							"introduced": "12.10.0"
						},
						{
							"fixed": "14.4.5"
						},
						{
							"introduced": "14.5.0"
						},
						{
							"fixed": "14.5.3"
						},
						{
							"introduced": "14.6.0"
						},
						{
							"fixed": "14.6.2"
						}
					]
				}
			],
			"database_specific": {
				"source": "https://github.com/bitnami/vulndb/tree/main/data/gitlab/BIT-gitlab-2022-0151.json"
			}
		}
	],
	"references": [
		{
			"type": "WEB",
			"url": "https://gitlab.com/gitlab-org/cves/-/blob/master/2022/CVE-2022-0151.json"
		},
		{
			"type": "WEB",
			"url": "https://gitlab.com/gitlab-org/gitlab/-/issues/348176"
		}
	],
	"database_specific": {
		"cpes": [
			"cpe:2.3:a:gitlab:gitlab:*:*:*:*:community:*:*:*",
			"cpe:2.3:a:gitlab:gitlab:*:*:*:*:enterprise:*:*:*",
			"cpe:2.3:a:gitlab:gitlab:*:*:*:*:*:*:*:*"
		],
		"severity": "Medium"
	}
}
