{
	"schema_version": "1.6.0",
	"id": "BIT-moodle-2021-3943",
	"modified": "2024-03-06T11:25:28.861Z",
	"published": "2024-03-06T11:07:54.805Z",
	"aliases": [
		"CVE-2021-3943",
		"GHSA-8jhp-2gcr-qw96"
	],
	"details": "A flaw was found in Moodle in versions 3.11 to 3.11.3, 3.10 to 3.10.7, 3.9 to 3.9.10 and earlier unsupported versions. A remote code execution risk when restoring backup files was identified.",
	"affected": [
		{
			"package": {
				"ecosystem": "Bitnami",
				"name": "moodle",
				"purl": "pkg:bitnami/moodle"
			},
			"severity": [
				{
					"type": "CVSS_V3",
					"score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H"
				}
			],
			"ranges": [
				{
					"type": "SEMVER",
					"events": [
						{
							"introduced": "3.9.0"
						},
						{
							"fixed": "3.9.10"
						},
						{
							"introduced": "3.10.0"
						},
						{
							"fixed": "3.10.7"
						},
						{
							"introduced": "3.11.0"
						},
						{
							"fixed": "3.11.3"
						}
					]
				}
			],
			"database_specific": {
				"source": "https://github.com/bitnami/vulndb/tree/main/data/moodle/BIT-moodle-2021-3943.json"
			}
		}
	],
	"references": [
		{
			"type": "WEB",
			"url": "https://bugzilla.redhat.com/show_bug.cgi?id=2021963"
		},
		{
			"type": "WEB",
			"url": "https://moodle.org/mod/forum/discuss.php?d=429095"
		}
	],
	"database_specific": {
		"cpes": [
			"cpe:2.3:a:moodle:moodle:*:*:*:*:*:*:*:*"
		],
		"severity": "Critical"
	}
}
