{
	"schema_version": "1.6.0",
	"id": "BIT-pillow-2021-28676",
	"modified": "2024-03-06T11:25:28.861Z",
	"published": "2024-03-06T11:03:35.091Z",
	"aliases": [
		"CVE-2021-28676",
		"GHSA-7r7m-5h27-29hp",
		"PYSEC-2021-92"
	],
	"details": "An issue was discovered in Pillow before 8.2.0. For FLI data, FliDecode did not properly check that the block advance was non-zero, potentially leading to an infinite loop on load.",
	"affected": [
		{
			"package": {
				"ecosystem": "Bitnami",
				"name": "pillow",
				"purl": "pkg:bitnami/pillow"
			},
			"severity": [
				{
					"type": "CVSS_V3",
					"score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H"
				}
			],
			"ranges": [
				{
					"type": "SEMVER",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "8.2.0"
						}
					]
				}
			],
			"database_specific": {
				"source": "https://github.com/bitnami/vulndb/tree/main/data/pillow/BIT-pillow-2021-28676.json"
			}
		}
	],
	"references": [
		{
			"type": "WEB",
			"url": "https://github.com/python-pillow/Pillow/commit/bb6c11fb889e6c11b0ee122b828132ee763b5856"
		},
		{
			"type": "WEB",
			"url": "https://github.com/python-pillow/Pillow/pull/5377"
		},
		{
			"type": "WEB",
			"url": "https://lists.debian.org/debian-lts-announce/2021/07/msg00018.html"
		},
		{
			"type": "WEB",
			"url": "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/MQHA5HAIBOYI3R6HDWCLAGFTIQP767FL/"
		},
		{
			"type": "WEB",
			"url": "https://pillow.readthedocs.io/en/stable/releasenotes/8.2.0.html#cve-2021-28676-fix-fli-dos"
		},
		{
			"type": "WEB",
			"url": "https://security.gentoo.org/glsa/202107-33"
		}
	],
	"database_specific": {
		"cpes": [
			"cpe:2.3:a:python:pillow:*:*:*:*:*:*:*:*"
		],
		"severity": "High"
	}
}
